name: Build python-ngspice

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: Build for Python ${{ matrix.python-version }} on Linux
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_24_x86_64

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
    # ngspice is not available as a prebuilt package on Debian 9, which is what manylinux_2_24 uses.
    # This uses the Debian repo for ngspice, which has better tagging than the official one :-/.
    - name: Build and install libngspice development files
      run: |
        apt-get update
        apt-get install -y gcc bison flex libtool autoconf automake
        cd /tmp
        git clone git@salsa.debian.org:electronics-team/ngspice.git
        git checkout debian/bullseye
        chmod +x autogen.sh compile_linux_shared.sh
        ./autogen.sh
        if [ $? -ne 0 ]; then  echo "./autogen.sh failed"; exit 1 ; fi
        ./compile_linux_shared.sh --enable-relpath

    - name: Get source code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create packages
      run: |
        python -m pip install build
        python -m build

    - name: Delocate shared objects
      run: auditwheel repair dist/*.whl

    - name: Remove Linux wheel
      run: rm dist/*-linux*.whl

    - name: Archive dist artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-linux-${{ matrix.python-version }}
        path: dist
