name: Test python-ngspice

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-linux:
    name: Test python-ngspice for Python ${{ matrix.python-version }} on Linux
    runs-on: ubuntu-latest
    env:
      python: python${{ matrix.python-version }}
    container: python:${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
    - name: Download built ngspice wheel
      uses: actions/download-artifact@v2
      with:
        name: "*.whl"
        path: wheelhouse

    - name: Install wheel
      run: |
        ${{ env.python }} -m pip install wheelhouse/*.whl

    - name: Run tests
      run: |
        ${{ env.python }} -m pip install pytest
        pytest
